# Clases sin lógica de negocio ? no aporta testearlas
sonar.coverage.exclusions=\
  **/dto/**,\
  **/config/**,\
  **/*Application.java

# Excluir del análisis de issues (Sonar no se queje de DTOs sin métodos, etc.)
sonar.exclusions=\
  **/dto/**,\
  **/*Application.java